### ISSUE TITLE
GatsbyJS demo

### ISSUE THREAD

**Issue by HriBB** [aokranj/website-pdkranj.si#22]
Končno mi je uspelo zrihtati tole https://pdkranj.gatsbyjs.io/

Za source sem vzel https://stg.pdkranj.si/, updejtal sem wp core na 6.0.1, updejtal sm vse plugine na zadnjo verzijo in dodal dva nove plugina [wp-graphql](https://github.com/wp-graphql/wp-graphql) in [wp-gatsby](https://github.com/gatsbyjs/wp-gatsby). GraphQL strežnik je dostopen na https://stg.pdkranj.si/graphql

Zakaj GatsbyJS?

Za primerjavo

https://pdkranj.gatsbyjs.io/
![gatsby](https://user-images.githubusercontent.com/4412324/180030649-224640b8-e48d-4b6b-9eb9-bcb4f438215a.png)

https://pdkranj.si
![wordpress](https://user-images.githubusercontent.com/4412324/180030651-36fae311-123b-42c8-a2bc-ae7bfaa29c70.png)

Tu bi poudaril, da sem se res potrudil, ko sem delal WP template za PD, zato ta primerjava ni najbolj relevantna. Če pa pogledamo AO Kranj website, je razlika mnogo bolj opazna.

https://aokranj.com/
![aokranj](https://user-images.githubusercontent.com/4412324/180031399-45158cf7-cde4-4ca2-867d-6749196007c0.png)

https://pdk.aokranj.com/
![pdk](https://user-images.githubusercontent.com/4412324/180035091-aaf08d83-3c31-4366-8f87-b5bbe166cdc7.png)

http://www.tkokranj.si/
![tkokranj](https://user-images.githubusercontent.com/4412324/180034528-44e744f7-9218-47fa-8c0b-ae71f7448f29.png)

**Comment by HriBB** [comment]
@JNastran a PD je pripravljen kej investirat v spletno stran?

**Comment by bostjan** [comment]
Zanimivo bi bilo videti primerjavo med AO stock verzijo (prod) in AO gatsby verzijo, vsaj glede na zgornje (razmeroma slabe) stock AO rezultate.

@HriBB, par vprašanj, ker niti ne poznam kaj GatsbyJS je ter kako deluje:


**Vprašanje #1** 
> Tu bi poudaril, da sem se res potrudil, ko sem delal WP template za PD

Ali je način implementacije PD teme tak, da je:
a) sam po sebi dovolj "performanten", da se dodan Gatsby niti ne pozna toliko, ali
b) tak, da je z njim implementacija GatsbyJS-ja dokaj preprosta?

PS: Absolutno lahko potrdim vložen trud, sem pogruntal to, ko sem analiziral PHP performance PD vs AO! :)


**Vprašanje #2** 
Ali bi bilo za podporo Gatsby-ju na AO potrebno _znatno_ predelati našo AO temo?
Oz. ali se GatsbyJS implementira "on top", da naša trenutna tema lahko laufa v ozadnju (bolj ali manj) nespremenjena?

**Comment by JNastran** [comment]
Dobro zgleda. Enkrat bo treba narediti korak naprej. 
Investicija? Saj veš, da spletno stran vsi drugače dojemajo kot mi. :) 
Bom na naslednjem upravnem odboru izpostavil.

**Comment by HriBB** [comment]
> **Vprašanje #1**
> 
> > Tu bi poudaril, da sem se res potrudil, ko sem delal WP template za PD
> 
> Ali je način implementacije PD teme tak, da je: a) sam po sebi dovolj "performanten", da se dodan Gatsby niti ne pozna toliko, ali b) tak, da je z njim implementacija GatsbyJS-ja dokaj preprosta?

Oboje. PD tema je optimizirana do te mere, da se GatsbyJS ne pozna toliko in je z njo implementacija GatsbyJS lažja.

> **Vprašanje #2** Ali bi bilo za podporo Gatsby-ju na AO potrebno _znatno_ predelati našo AO temo? Oz. ali se GatsbyJS implementira "on top", da naša trenutna tema lahko laufa v ozadnju (bolj ali manj) nespremenjena?

AO Kranj Gatsby verzijo imam že pripravljeno, samo je toliko vsebine, da mi vmes crkne image download. Pa verjetno free netlify plan ne zajema toliko prostora, ker mislim da imamo preko 20 GB. Problem pri AO kranj je količina vsebine in bi moral verjetno delati SSR ali celo SSG, to je pa bolj primeren https://nextjs.org/

**Comment by bostjan** [comment]
AO image dataset je cca 40GB trenutno.

A dejansko rabis cel image dataset pri roki, ali lahko samo linkas kar na zunanje URLje za slike, in se slike pac loadajo v browser od drugje?

**Comment by HriBB** [comment]
GatsbyJS ponuja možnost optimizacije slik z [`gatsby-plugin-image`](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/). Ta plugin doda podporo za lazy load, blurry image preview, resize for mobile itd. V primeru AO Kranj, ker imamo toliko podatkov, to ne pride v poštev in bi morali slike loadati direktno iz https://aokranj.com/.

Bom v kratkem šel čez cel workflow in naredil Gatsby demo še za AO Kranj ;)

**Comment by bostjan** [comment]
@HriBB, sedaj ko imas svoj public dev okolje, a je se smiselno tole takoj deployat na stg/prod? Sprasujem namrec zaradi update-ov WP-ja.

Imamo dve opciji:
- Ali pustimo tole novo kodo (ki je zajeta v dveh plugin-ih (`wp-gatsby` in `wp-graphql`) in eni temi (`pdkranj-dev`)) v repotu ter na stg/prod te stvari niso enablane, dokler niso ready. Ker niso enablane, naceloma ne motijo izvajanja preostalega dela website-a.
- Ali pa odstranimo to novo kodo iz `master` brancha, ter raje stvar pripravimo v nekem feature branchu, dokler ni ready za merge/deployment.

Osebno mi je vseeno, katera opcija je (ker tudi prva mislim da ni prenevarna, ceprav naceloma ne maram mrtve kode v produkciji).

**Comment by HriBB** [comment]
@bostjan ja najboljš da se `wp-graphql` in `wp-gatsby` popolnoma odstrani iz `master` brancha in se ga doda samo v moj `staging` oziroma `dev` branch. Bom preveril situacijo, ko bom mel spet kej elana za delo na temle ;)

**Comment by bostjan** [comment]
Odstranjeno (z revertanjem, tako da je vse se vedno shranjeno v git zgodovini).
