### ISSUE TITLE
Preglej dependabot alerte

### ISSUE THREAD

**Issue by bostjan** [aokranj/website-pdkranj.si#24]
Tole javlja GitHub:
![image](https://user-images.githubusercontent.com/107080/187802240-923ff1ee-e86e-4f07-9c15-6b41180b79b1.png)

@HriBB, kaj je tu za naredit?

**Comment by HriBB** [comment]
@bostjan načeloma se večino vulnerable paketov ne uporablja, oziroma se vsaj ne uporablja direktno.

Prvič vidim tale `undici` package, najbrž ga namesti kak package kot `peerDependency` in zato dependabot zajamra. Jest običajno na hitro preletim paketke in če opazim nekaj, kar uporabljam direktno ali vem da se uporablja indirektno, potem preverim situacijo ... v nasprotnem primeru pa samo briše alete :)

**Comment by bostjan** [comment]
PR #25 je odstranil relevantne zadeve.
