### ISSUE TITLE
Email iz PDKranj pade v spam

### ISSUE THREAD

**Issue by HriBB** [aokranj/website-pdkranj.si#29]
![Screenshot from 2022-10-05 13-28-57](https://user-images.githubusercontent.com/4412324/194050297-3636dac4-39ed-4fd4-9f72-5c59037c9496.png)

![Screenshot from 2022-10-05 13-27-28](https://user-images.githubusercontent.com/4412324/194050188-a5875e28-6545-44af-bce2-c813b5c17484.png)

**Comment by JNastran** [comment]
Pa ne, da je Bojč od mrtvih vstal??? 😆

**Comment by bostjan** [comment]
@HriBB, @JNastran, sicer email je od PD Kranj, ampak kot vidim po screenshot-ih, nima nobene zveze s `pdkranj.si` domeno. Izgleda, kot da `vodniki.pdkranj [AT} gmail.com` pošilja mailing preko [Mailchimp-a](https://mailchimp.com/).

Sicer nisem ekspert, ampak sumim, da Googlu ni ful všeč, da nekdo uporablja `@gmail.com` domeno za "spamanje" preko nekega tretjega servisa - [tudi njihov SPF zapis tako pravi](https://www.spf-record.com/spf-lookup/gmail.com).

@JNastran, a lahko tole spraviš do vodnikov, oz. do osebe, ki te mailinge dejansko pošilja, pa naj uredijo z Mailchimp-om. 

Sumim, da bo treba urediti naslednje:
* Kreirati account pod domeno `@pdkranj.si`
* Dodati mailchimp-ove SPF zapise v DNS od `pdkranj.si`

**Comment by JNastran** [comment]
Velja. Javim Sušotu.
